/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicProcessWorkflowsRouteImport } from './routes/api/public/process-workflows'
import { Route as ApiPublicProcessScheduledMessagesRouteImport } from './routes/api/public/process-scheduled-messages'
import { Route as ApiPublicProcessCampaignsRouteImport } from './routes/api/public/process-campaigns'
import { Route as ApiPublicEvolutionWebhookRouteImport } from './routes/api/public/evolution-webhook'
import { Route as ApiPublicChatwootWebhookRouteImport } from './routes/api/public/chatwoot-webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicProcessWorkflowsRoute =
  ApiPublicProcessWorkflowsRouteImport.update({
    id: '/api/public/process-workflows',
    path: '/api/public/process-workflows',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProcessScheduledMessagesRoute =
  ApiPublicProcessScheduledMessagesRouteImport.update({
    id: '/api/public/process-scheduled-messages',
    path: '/api/public/process-scheduled-messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProcessCampaignsRoute =
  ApiPublicProcessCampaignsRouteImport.update({
    id: '/api/public/process-campaigns',
    path: '/api/public/process-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvolutionWebhookRoute =
  ApiPublicEvolutionWebhookRouteImport.update({
    id: '/api/public/evolution-webhook',
    path: '/api/public/evolution-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChatwootWebhookRoute =
  ApiPublicChatwootWebhookRouteImport.update({
    id: '/api/public/chatwoot-webhook',
    path: '/api/public/chatwoot-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/chatwoot-webhook': typeof ApiPublicChatwootWebhookRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/process-campaigns': typeof ApiPublicProcessCampaignsRoute
  '/api/public/process-scheduled-messages': typeof ApiPublicProcessScheduledMessagesRoute
  '/api/public/process-workflows': typeof ApiPublicProcessWorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/chatwoot-webhook': typeof ApiPublicChatwootWebhookRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/process-campaigns': typeof ApiPublicProcessCampaignsRoute
  '/api/public/process-scheduled-messages': typeof ApiPublicProcessScheduledMessagesRoute
  '/api/public/process-workflows': typeof ApiPublicProcessWorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/chatwoot-webhook': typeof ApiPublicChatwootWebhookRoute
  '/api/public/evolution-webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/process-campaigns': typeof ApiPublicProcessCampaignsRoute
  '/api/public/process-scheduled-messages': typeof ApiPublicProcessScheduledMessagesRoute
  '/api/public/process-workflows': typeof ApiPublicProcessWorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/features'
    | '/sitemap.xml'
    | '/dashboard'
    | '/api/public/chatwoot-webhook'
    | '/api/public/evolution-webhook'
    | '/api/public/process-campaigns'
    | '/api/public/process-scheduled-messages'
    | '/api/public/process-workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/features'
    | '/sitemap.xml'
    | '/dashboard'
    | '/api/public/chatwoot-webhook'
    | '/api/public/evolution-webhook'
    | '/api/public/process-campaigns'
    | '/api/public/process-scheduled-messages'
    | '/api/public/process-workflows'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/features'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/api/public/chatwoot-webhook'
    | '/api/public/evolution-webhook'
    | '/api/public/process-campaigns'
    | '/api/public/process-scheduled-messages'
    | '/api/public/process-workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicChatwootWebhookRoute: typeof ApiPublicChatwootWebhookRoute
  ApiPublicEvolutionWebhookRoute: typeof ApiPublicEvolutionWebhookRoute
  ApiPublicProcessCampaignsRoute: typeof ApiPublicProcessCampaignsRoute
  ApiPublicProcessScheduledMessagesRoute: typeof ApiPublicProcessScheduledMessagesRoute
  ApiPublicProcessWorkflowsRoute: typeof ApiPublicProcessWorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/process-workflows': {
      id: '/api/public/process-workflows'
      path: '/api/public/process-workflows'
      fullPath: '/api/public/process-workflows'
      preLoaderRoute: typeof ApiPublicProcessWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-scheduled-messages': {
      id: '/api/public/process-scheduled-messages'
      path: '/api/public/process-scheduled-messages'
      fullPath: '/api/public/process-scheduled-messages'
      preLoaderRoute: typeof ApiPublicProcessScheduledMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-campaigns': {
      id: '/api/public/process-campaigns'
      path: '/api/public/process-campaigns'
      fullPath: '/api/public/process-campaigns'
      preLoaderRoute: typeof ApiPublicProcessCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution-webhook': {
      id: '/api/public/evolution-webhook'
      path: '/api/public/evolution-webhook'
      fullPath: '/api/public/evolution-webhook'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatwoot-webhook': {
      id: '/api/public/chatwoot-webhook'
      path: '/api/public/chatwoot-webhook'
      fullPath: '/api/public/chatwoot-webhook'
      preLoaderRoute: typeof ApiPublicChatwootWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicChatwootWebhookRoute: ApiPublicChatwootWebhookRoute,
  ApiPublicEvolutionWebhookRoute: ApiPublicEvolutionWebhookRoute,
  ApiPublicProcessCampaignsRoute: ApiPublicProcessCampaignsRoute,
  ApiPublicProcessScheduledMessagesRoute:
    ApiPublicProcessScheduledMessagesRoute,
  ApiPublicProcessWorkflowsRoute: ApiPublicProcessWorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
